steps:
    - name: 'gcr.io/cloud-builders/docker'
        args: ['build', '-t', 'gcr.io/macro-context-410815/trainingimage', '.']
    - name: 'gcr.io/cloud-builders/docker'
        args: ['push', 'gcr.io/macro-context-410815/trainingimage']